language: r
r:
  - bioc-devel
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev libmagick++-dev
# for codecov
r_packages:
  - covr
  - magick
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
cache:
  packages: true
  directories:
  - docs
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    recipients:
      - felix.gm.ernst-travis@outlook.com
    on_success: change
    on_failure: always
