---
title: "ModDNAString alphabet"
author: "Felix G.M. Ernst & Denis L.J. Lafontaine"
date: "`r Sys.Date()`"
package: Modstrings
abstract: >
  Details on the DNA modification alphabet used by the Modstrings package
output:
  BiocStyle::html_document:
    df_print: paged
vignette: >
  %\VignetteIndexEntry{Modstrings-DNA-alphabet}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown(css.files = c("custom.css"))
```

The alphabets for the modifications used in this package are based on the
compilation of DNA modifications by the Hoffman lab [@Sood.2019]. The alphabet
was modified to make it compatible for the `Modstrings` package.

If modifications are missing, let us know.

```{r alphabet, echo=FALSE}
suppressPackageStartupMessages(library(Modstrings))
df <- as.data.frame(Modstrings:::additionalInfo(Modstrings:::MOD_DNA_STRING_CODEC))
df <- df[df$abbrev != "",]
colnames(df) <- c("modification",
                  "short name",
                  "nomenclature",
                  "orig. base",
                  "abbreviation")
knitr::kable(
  df, caption = 'List of supported DNA modifications by ModDNAString objects.'
)
```

```{r sessioninfo}
sessionInfo()
```

# References
